display:
    name: 'Rogue'
    lore:
    - 'His important damage burst potential and'
    - 'his lack of health forces him to one'
    - 'shot his targets before being taken down.'
    attribute-lore:
    - '&a+ &7Attack Speed'
    - '&c- &7Max Health'
    - '&c- &7Movement Speed'
    - ''
    - '&8&lStrength'
    - '&7  Attack Damage: &c1 &7(+&c0&7)'
    - '&7  Attack Speed: &c4.2 &7(+&c0.05&7)'
    - '&7  Max Health: &c18 &7(+&c0&7)'
    - ''
    - '&8&lDexterity'
    - '&7  Knockback Resistance: &a0% &7(+&a0%&7)'
    - '&7  Movement Speed: &a21 &7(+&a0&7)'
    - '&7  Speed Malus Reduction: &a0% &7(+&a0%&7)'
    - ''
    - '&8&lIntellect'
    - '&7  Max Mana: &920 &7(+&90&7)'
    - '&7  Health Regen: &90.1 &7(+&90&7)'
    - '&7  Mana Regen: &90.166 &7(+&90&7)'
    item: LEATHER_BOOTS

# Must match an existing exp curve filename from the 'expcurves' folder
exp-curve: levels

# Players cannot go further than Lvl 100
max-level: 100

triggers:
    level-up:
    - 'command{format="mmocore admin skill-points give %player% 1"}'

options:
    off-combat-mana-regen: true
    off-combat-health-regen: true

cast-particle:
    particle: SPELL_WITCH

skills:
    DEEP_WOUND:
        level: 1
        max-level: 30
    WEAKEN:
        level: 3
        max-level: 30
    EMPOWERED_ATTACK:
        level: 5
        max-level: 30
    COMBO_ATTACK:
        level: 7
        max-level: 30
    EVADE:
        level: 9
        max-level: 30
    FURTIVE_STRIKE:
        level: 4
        max-level: 30
    MINOR_HEALINGS:
        level: 10
        max-level: 30
    SNEAKY_PICKY:
        level: 2
        max-level: 20

attributes:
    attack-speed:
        base: 4.2
        per-level: 0.05
    max-health:
        base: 18
        per-level: 0
    movement-speed:
        base: .105
        per-level: 0

# Experience sources for main class experience.
main-exp-sources:
- 'killmob{type=ZOMBIE;amount=1-3}'
- 'killmob{type=ENDERMAN;amount=6-9}'
