# DO NOT TOUCH
config-version: 4

# Edit general plugin number formatting here.
number-format:
  decimal-separator: .

# This is the formula for how defense works. It does
# NOT apply operators precedence. Placeholders:
# #damage# - Damage Dealt
# #defense# - Player Defense
defense-application: '#damage# * (1 - (#defense# / (#defense# + 100)))'

# Allows to scale health up/down to a specific
# amount so extra health does not fill up the screen.
# Requires a SERVER reload when changed.
# Delay should be used if your Users experience issues revolving around seeing too many hearts still. This can occur with plugins such as MySQL Inventory Bridge
# The delay is in ticks. 20 ticks = 1 second
health-scale:
  enabled: true
  scale: 20
  delay: 0

# Set to false to prevent players from dealing damage to other
# players using abilities. This is an useful option for PvE servers.
player-ability-damage: true

critical-strikes:
  weapon:
    # Default = 2 meaning crits deal 200% of the initial damage
    coefficient: 2
    cooldown: 3
    max-chance: 80
  skill:
    # Default = 1.5 meaning crits deal 150% of the initial damage
    coefficient: 1.5
    cooldown: 3
    max-chance: 80

# 플레이어가 서버에 접속했을 때 이동속도를 0.1 (기본) 으로 설정할 것인지
fix-movement-speed: true
